### ISSUE TITLE
Code missing?

### ISSUE THREAD

**Issue by renners7777** [Kinsta-Academy/node-js-photo-sharing-app#4]
In chapter 5.6, it says "Next, To use sequelize, we first open a connection to the database. In our index.js file, let's write some code:" However, following that there is no code. Should there be something there?

**Comment by drewlearns** [comment]
> Next, To use sequelize, we first open a connection to the database. In our index.js file, let's write some code:
Should just be:
"Next, To use sequelize, we first open a connection to the database."
